# Generated by Django 4.2.13 on 2024-06-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_student_is_active_student_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
    ]
