# Generated by Django 4.2.13 on 2024-06-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0005_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
