# Generated by Django 4.2.13 on 2024-06-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_courses',
            field=models.ManyToManyField(related_name='completed_by', to='courses.course'),
        ),
    ]
