# Generated by Django 5.0.6 on 2024-06-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='days',
            field=models.CharField(choices=[('S,T,T', 'Sunday, Tuesday, Thursday'), ('M,W', 'Monday, Wednesday'), ('S,T', 'Sunday, Tuesday'), ('S,T', 'Sunday, Thursday'), ('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('w', 'Wednesday'), ('T', 'Thursday')], max_length=50, null=True),
        ),
    ]
