# Generated by Django 4.2.13 on 2024-06-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_student_completed_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='completed_courses',
        ),
    ]
