# Generated by Django 4.2.13 on 2024-06-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_student_completed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
